name: 'Check Dependencies In Pull Request'
description: 'A Github Action that publishes a comment in your PR notifying what Gradle dependencies need to be updated'
inputs:
  pull_request_url:
    description: 'Pull request url'
    required: true
  github_token:
    description: 'Github token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pull_request_url }}
    - ${{ inputs.github_token }}
branding:
  icon: 'arrow-up-circle'
  color: blue